// Generated by CoffeeScript 1.6.3
(function() {
  require('backbone-orm/lib/client_utils').loadDependencies([
    {
      symbol: 'superagent',
      path: 'superagent'
    }
  ]);

  module.exports = {
    sync: require('./sync')
  };

}).call(this);
